#!/usr/bin/env python3
"""Render docs/API.md from the FastAPI app's OpenAPI schema (so the reference cannot drift from the code)."""

from __future__ import annotations

import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from backend.app.main import create_app  # noqa: E402
from backend.app.settings import Settings  # noqa: E402


def main() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        app = create_app(Settings(db_path=f"{tmp}/x.db"))
        spec = app.openapi()
    lines = [
        "# API reference",
        "",
        "> Generated by `scripts/render_api_docs.py` from the FastAPI OpenAPI schema. Interactive docs: `/docs` on a running server.",
        "",
        f"**{spec['info']['title']}** v{spec['info']['version']} — {spec['info'].get('description', '')}",
        "",
        "All payloads carry a `disclosure` field: synthetic data, research prototype, not a detection system.",
        "",
        "| Method | Path | Parameters / body | Success | Errors |",
        "|---|---|---|---|---|",
    ]
    for path, ops in spec["paths"].items():
        for method, op in ops.items():
            params = [f"`{p['name']}`" + ("*" if p.get("required") else "") for p in op.get("parameters", [])]
            body = (
                op.get("requestBody", {}).get("content", {}).get("application/json", {}).get("schema", {}).get("$ref")
            )
            if body:
                params.append(f"body `{body.split('/')[-1]}`")
            codes = [c for c in op["responses"] if c != "422"]
            ok = ", ".join(c for c in codes if c.startswith("2")) or "200"
            errs = ", ".join(sorted({"422"} | {c for c in codes if not c.startswith("2")}))
            lines.append(f"| {method.upper()} | `{path}` | {', '.join(params) or '—'} | {ok} | {errs} |")
    lines += [
        "",
        "`*` = required. Path parameters are validated (`case_id` must match `^RG-(LI|HI)-\\d{1,6}-\\d{8}$`).",
        "",
        "## Request models",
        "",
    ]
    for name, sch in spec["components"]["schemas"].items():
        if name in ("HTTPValidationError", "ValidationError"):
            continue
        props = sch.get("properties", {})
        lines.append(f"### `{name}`")
        for k, v in props.items():
            t = v.get("type") or v.get("$ref", "").split("/")[-1] or "enum/any"
            extra = ", ".join(
                f"{a}={v[a]}"
                for a in ("minimum", "maximum", "exclusiveMinimum", "maxLength", "minLength", "pattern", "enum")
                if a in v
            )
            req = "required" if k in sch.get("required", []) else "optional"
            lines.append(f"* `{k}`: {t} ({req}){' — ' + extra if extra else ''}")
        lines.append("")
    lines += [
        "## Behaviour notes",
        "",
        "* **Auth:** none by default (public synthetic demo). If `RISKGRAPH_API_KEY` is set, `POST /api/cases/{id}/decision` and `GET /api/audit` require header `X-API-Key`.",
        "* **Decisions** are labelled `simulated: true` while `RISKGRAPH_DEMO_MODE=true`.",
        "* **Rate limit:** `RISKGRAPH_RATE_LIMIT_PER_MIN` per client address (default 120); `/health` is exempt; exceeded → `429` with `Retry-After`.",
        "* **CORS:** exact origins from `RISKGRAPH_CORS_ORIGINS`; no credentials.",
        "* **`/api/predict`** requires exactly the model's feature names (see `artifacts/demo/<DS>/model/feature_schema.json`); unknown/missing/non-finite → `422`.",
        "* **`/api/simulate`** recomputes the decision engine on the stored test-window score stream for arbitrary policy, α ∈ (0, 0.5] and capacity multiplier ∈ [0.1, 10].",
        "* Errors never include stack traces; unexpected failures return `500` with a `request_id`.",
        "",
    ]
    out = ROOT / "docs" / "API.md"
    out.write_text("\n".join(lines))
    print(f"wrote {out} ({len(lines)} lines, {sum(len(o) for o in spec['paths'].values())} operations)")


if __name__ == "__main__":
    main()
